Time to live
AEB-labs/cruddl pull request #172
Opened 2020-09-04 06:20 UTC by mfusser

2020-09-04 12:49 UTC, Yogu requested changes

2020-09-04 12:49 UTC, Yogu commented on src/model/implementation/time-to-live.ts
> +        this.traversePath(mess => context.addMessage(mess));
we should validate `expireAfterDays` (positive integer) and `typeName` (exists and is a root entity type) here

2020-11-20 07:29 UTC, mfusser commented
Is this ready to be merged? it says "change requested by yogu" but i can't see any unsolved requested changes.

2020-11-20 10:58 UTC, Yogu approved these changes

2020-11-20 10:58 UTC, merged